export const KB = [
  // ── WiFi ────────────────────────────────────────────────────
  {
    id: 'wifi-001',
    title: 'Laptop not detecting WiFi networks',
    category: 'WiFi',
    tags: ['wifi','driver','hardware'],
    severity: 'medium',
    causes: ['WiFi adapter driver missing or corrupt','WiFi physically disabled (Fn key or BIOS switch)','WiFi adapter hardware failure','WLAN AutoConfig service stopped'],
    steps: [
      'Check Fn + WiFi key — look for WiFi LED indicator',
      'Open Device Manager → Network Adapters → look for yellow warning on WiFi adapter',
      'If adapter missing: Action → Scan for hardware changes',
      'Right-click adapter → Update driver → Search automatically',
      'If driver fails: Download Intel AX200/AX201 driver from manufacturer site',
      'Services → WLAN AutoConfig → set to Automatic and Start',
      'If still missing: reseat WiFi card (M.2 slot under keyboard or bottom panel)',
    ],
    tools: ['Device Manager', 'services.msc', 'Intel Driver & Support Assistant'],
    time: '10–30 min',
  },
  {
    id: 'wifi-002',
    title: 'WiFi connects but no internet access',
    category: 'WiFi',
    tags: ['wifi','network','dns'],
    severity: 'low',
    causes: ['DNS server issue','IP conflict','Corrupted TCP/IP stack','Router DHCP exhausted'],
    steps: [
      'Run: ipconfig /release then ipconfig /renew',
      'Run: ipconfig /flushdns',
      'Run: netsh int ip reset and netsh winsock reset',
      'Set DNS manually to 8.8.8.8 (Google) or 1.1.1.1 (Cloudflare)',
      'Restart router — check if other devices have same issue',
      'Check router DHCP range — may be exhausted',
    ],
    tools: ['cmd (admin)', 'ipconfig', 'netsh'],
    time: '5–15 min',
  },
  {
    id: 'wifi-003',
    title: 'WiFi drops frequently / unstable connection',
    category: 'WiFi',
    tags: ['wifi','driver','power'],
    severity: 'medium',
    causes: ['Power management turning off WiFi adapter','Outdated driver','Channel congestion','Weak signal'],
    steps: [
      'Device Manager → WiFi adapter → Properties → Power Management → uncheck "Allow computer to turn off to save power"',
      'Update WiFi driver to latest version',
      'Change WiFi channel on router (use 1, 6, or 11 for 2.4GHz)',
      'Switch to 5GHz band if router supports it',
      'Check signal strength — move closer to router or add repeater',
      'Set power plan to High Performance',
    ],
    tools: ['Device Manager', 'Router admin panel'],
    time: '5–20 min',
  },

  // ── Battery ─────────────────────────────────────────────────
  {
    id: 'bat-001',
    title: 'Battery not charging — stuck at 0%',
    category: 'Battery',
    tags: ['battery','charging','ec','bios'],
    severity: 'high',
    causes: ['EC (Embedded Controller) firmware glitch','Faulty charging cable or adapter','Dead battery cell','BIOS battery calibration needed'],
    steps: [
      'Power off completely — remove AC adapter and battery (if removable)',
      'Hold power button for 30 seconds (EC reset)',
      'Reconnect battery, then AC — power on',
      'If no change: try a different known-good charger',
      'Check charger LED on laptop — if no light, adapter may be dead',
      'Boot into BIOS — check if battery is detected',
      'If battery detected but 0%: battery may need calibration or replacement',
      'Run: powercfg /batteryreport — check Design vs Full Charge Capacity',
    ],
    tools: ['powercfg /batteryreport', 'BatteryInfoView (NirSoft)', 'BIOS'],
    time: '10–45 min',
  },
  {
    id: 'bat-002',
    title: 'Battery drains extremely fast',
    category: 'Battery',
    tags: ['battery','wear','performance'],
    severity: 'medium',
    causes: ['High battery wear (>40%)', 'Background processes using excessive CPU', 'High screen brightness', 'Battery calibration off'],
    steps: [
      'Run: powercfg /batteryreport — check Wear Level percentage',
      'If wear >40%: recommend battery replacement',
      'Check Task Manager → CPU/Power usage by background apps',
      'Reduce screen brightness to 50%',
      'Change power plan to Power Saver',
      'Disable Bluetooth and WiFi when not needed',
      'Update drivers — outdated GPU drivers cause high power draw',
    ],
    tools: ['powercfg', 'Task Manager', 'BatteryInfoView'],
    time: '15–30 min',
  },
  {
    id: 'bat-003',
    title: 'Laptop only works on AC, battery not recognized',
    category: 'Battery',
    tags: ['battery','driver','bios'],
    severity: 'high',
    causes: ['Battery completely dead (0 capacity)', 'Battery driver corrupt', 'Faulty battery connector', 'BIOS not detecting battery'],
    steps: [
      'Device Manager → Batteries → Microsoft ACPI-Compliant Control Method Battery',
      'Uninstall battery device → reboot → Windows reinstalls driver',
      'If not detected in Device Manager: reseat battery connector on motherboard',
      'Check battery connector for bent pins',
      'Test with known-good battery if available',
      'Check BIOS for battery detection',
    ],
    tools: ['Device Manager', 'BIOS'],
    time: '20–60 min',
  },

  // ── USB ─────────────────────────────────────────────────────
  {
    id: 'usb-001',
    title: 'USB port not working / device not detected',
    category: 'USB',
    tags: ['usb','driver','hardware'],
    severity: 'medium',
    causes: ['USB controller driver issue', 'USB selective suspend enabled', 'Port physically damaged', 'USB power management issue'],
    steps: [
      'Try the device in a different USB port',
      'Try a different known-good device in the same port',
      'Device Manager → Universal Serial Bus Controllers → check for errors',
      'Right-click each USB Root Hub → Properties → Power Management → uncheck "Allow computer to turn off"',
      'Uninstall all USB Root Hub devices → Action → Scan for hardware changes',
      'Power Management → Change plan settings → USB selective suspend → Disabled',
      'If port dead: check for physical damage, inspect connector pins',
    ],
    tools: ['Device Manager', 'Power Options'],
    time: '10–30 min',
  },
  {
    id: 'usb-002',
    title: 'USB 3.0 device running at USB 2.0 speed',
    category: 'USB',
    tags: ['usb','performance','driver'],
    severity: 'low',
    causes: ['Device plugged into USB 2.0 port', 'USB 3.0 driver not installed', 'Intel USB 3.0 controller driver missing'],
    steps: [
      'Check which port you are using — USB 3.0 ports are usually marked in blue',
      'Device Manager → Universal Serial Bus Controllers → look for "USB 3.0 eXtensible Host Controller"',
      'If missing: download Intel USB 3.0 driver from manufacturer site',
      'Ensure the USB cable itself supports 3.0 (some cables are 2.0 only)',
      'Test device directly without a hub',
    ],
    tools: ['Device Manager', 'CrystalDiskMark (speed test)'],
    time: '10–20 min',
  },

  // ── Overheating ─────────────────────────────────────────────
  {
    id: 'heat-001',
    title: 'Laptop overheating / CPU throttling',
    category: 'Overheating',
    tags: ['thermal','cpu','fan','paste'],
    severity: 'high',
    causes: ['Clogged heatsink/fan with dust', 'Dried thermal paste (>3–4 years)', 'Fan not spinning at full speed', 'Blocked air vents'],
    steps: [
      'Check CPU temp with HWiNFO64 or HackRore — if >85°C at idle, heat is the issue',
      'Power off, disassemble — clean fan and heatsink with compressed air',
      'Remove old thermal paste with isopropyl alcohol (90%+)',
      'Apply fresh thermal paste (Noctua NT-H1 or MX-4) — pea-sized dot on CPU die',
      'Ensure all heatsink screws are tight and in correct order (cross pattern)',
      'Test fan — should spin up under load. Replace if bearing is noisy or stuck',
      'Place laptop on hard flat surface — soft surfaces block vents',
      'Check BIOS for fan control settings — reset to default',
    ],
    tools: ['HWiNFO64', 'HackRore ThermalModule', 'Screwdrivers', 'IPA 90%+', 'Thermal paste'],
    time: '45–90 min',
  },
  {
    id: 'heat-002',
    title: 'Fan making loud grinding / rattling noise',
    category: 'Overheating',
    tags: ['fan','noise','hardware'],
    severity: 'medium',
    causes: ['Dust caught in fan blades', 'Fan bearing worn out', 'Fan blade cracked'],
    steps: [
      'Open laptop — locate fan',
      'Clean fan blades with soft brush or compressed air',
      'Spin fan manually — if it wobbles or catches, bearing is failing',
      'Replace fan — source fan by laptop model (iFixit, eBay)',
      'Use same fan model or compatible replacement',
    ],
    tools: ['Compressed air', 'Screwdrivers'],
    time: '30–60 min',
  },

  // ── Display ─────────────────────────────────────────────────
  {
    id: 'disp-001',
    title: 'Laptop screen not turning on (backlight dead)',
    category: 'Display',
    tags: ['display','backlight','inverter','gpu'],
    severity: 'high',
    causes: ['Backlight cable loose or damaged', 'Inverter board failed (older CCFL screens)', 'GPU issue', 'Screen itself failed'],
    steps: [
      'Shine a torch at the screen — if you can faintly see an image, backlight is dead (not GPU)',
      'Connect external monitor via HDMI/VGA — if that works, issue is screen/backlight not GPU',
      'Check display cable connection on motherboard and screen — may be loose',
      'For CCFL screens: test/replace inverter board',
      'For LED screens with dead backlight: replace screen or backlight strip',
      'If external monitor also blank: GPU or graphics driver issue',
    ],
    tools: ['Torch', 'External monitor', 'Multimeter (advanced)'],
    time: '30–120 min',
  },
  {
    id: 'disp-002',
    title: 'Screen has lines, flickering, or artifacts',
    category: 'Display',
    tags: ['display','cable','gpu','driver'],
    severity: 'medium',
    causes: ['Display cable loose or damaged', 'GPU driver issue', 'Screen panel failing', 'Refresh rate mismatch'],
    steps: [
      'Connect external monitor — if external is fine, issue is screen/cable',
      'Wiggle hinge gently — if flicker changes, cable is damaged at hinge flex point',
      'Update GPU driver — DDU clean uninstall then reinstall latest',
      'Check Display Properties → refresh rate matches screen spec',
      'Open back of lid — reseat display cable at both ends',
      'If cable is visibly damaged at hinge: replace display cable (~£15–30)',
    ],
    tools: ['DDU (Display Driver Uninstaller)', 'External monitor'],
    time: '20–90 min',
  },

  // ── Storage ─────────────────────────────────────────────────
  {
    id: 'ssd-001',
    title: 'NVMe SSD not showing in Windows',
    category: 'Storage',
    tags: ['nvme','ssd','bios','driver'],
    severity: 'high',
    causes: ['BIOS set to RAID mode instead of AHCI', 'NVMe driver not installed', 'M.2 slot not enabled in BIOS', 'Physical seating issue'],
    steps: [
      'Check BIOS → Storage Controller mode → set to AHCI (not RAID)',
      'Check BIOS → M.2 slot enable/disable setting',
      'Reseat the M.2 SSD — ensure screw holds it flat',
      'Check if SSD uses PCIe x4 — some older slots are x2 only (NVMe will show but slow)',
      'Install Intel RST or AMD StoreMI driver if required',
      'Disk Management → if SSD appears unallocated, initialize and format it',
      'Try SSD in another machine — if also not detected, SSD may be dead',
    ],
    tools: ['BIOS', 'Disk Management', 'CrystalDiskInfo'],
    time: '20–60 min',
  },
  {
    id: 'ssd-002',
    title: 'HDD/SSD making clicking sounds (click of death)',
    category: 'Storage',
    tags: ['hdd','smart','hardware','data-recovery'],
    severity: 'critical',
    causes: ['HDD read/write head failure', 'Physical platter damage', 'Power issue causing heads to park repeatedly'],
    steps: [
      '⚠ STOP USING THE DRIVE IMMEDIATELY — every read increases data loss risk',
      'Do NOT run chkdsk on a clicking drive — it worsens damage',
      'Back up data immediately if drive is still partially accessible',
      'Use TestDisk or Recuva for data recovery attempt',
      'For professional recovery: send to clean room data recovery service',
      'This is a physical hardware failure — drive needs replacement',
      'Check SMART with CrystalDiskInfo — will show reallocated sectors',
    ],
    tools: ['CrystalDiskInfo', 'TestDisk', 'Recuva', 'Clonezilla'],
    time: 'Immediate action required',
  },
  {
    id: 'ssd-003',
    title: 'Windows very slow boot — SSD or HDD issue',
    category: 'Storage',
    tags: ['performance','ssd','startup'],
    severity: 'medium',
    causes: ['Drive nearly full (>90%)', 'Too many startup items', 'Drive health degrading', 'Windows search indexing'],
    steps: [
      'Check drive health with CrystalDiskInfo or HackRore SMART module',
      'Check free space — SSD needs 15%+ free to perform well',
      'Task Manager → Startup tab → disable unnecessary startup programs',
      'Run: cleanmgr — clean temp files, old updates',
      'Check for pending Windows Updates — sometimes causes slow boot',
      'Run disk benchmark — SSD should read >400MB/s (SATA) or >1500MB/s (NVMe)',
      'If read speed <100MB/s on SSD: drive is failing, replace it',
    ],
    tools: ['CrystalDiskMark', 'CrystalDiskInfo', 'HackRore Module 17', 'cleanmgr'],
    time: '15–45 min',
  },

  // ── Camera ──────────────────────────────────────────────────
  {
    id: 'cam-001',
    title: 'Camera not detected / not working',
    category: 'Camera',
    tags: ['camera','driver','privacy'],
    severity: 'medium',
    causes: ['Camera disabled in Device Manager', 'Camera driver corrupt or missing', 'Privacy switch/BIOS setting disabled', 'Windows privacy setting blocking camera'],
    steps: [
      'Device Manager → Cameras → check if camera appears',
      'If camera has yellow warning: right-click → Update driver',
      'Check for physical privacy shutter — some laptops have a slider over lens',
      'BIOS → check for camera enable/disable option',
      'Settings → Privacy → Camera → allow apps to access camera',
      'Uninstall camera in Device Manager → reboot → reinstall driver',
      'If camera not in Device Manager at all: hardware may be disconnected or dead',
      'Open back cover → check camera cable connection',
    ],
    tools: ['Device Manager', 'Settings (Privacy)', 'BIOS'],
    time: '10–30 min',
  },

  // ── Bluetooth ────────────────────────────────────────────────
  {
    id: 'bt-001',
    title: 'Bluetooth not pairing with devices',
    category: 'Bluetooth',
    tags: ['bluetooth','driver','pairing'],
    severity: 'low',
    causes: ['Device not in pairing mode', 'Bluetooth driver issue', 'Too many paired devices saved'],
    steps: [
      'Ensure target device is in pairing mode (usually hold button for 5 seconds)',
      'Remove device from saved list → re-pair fresh',
      'Device Manager → Bluetooth → check for driver issues',
      'Update Bluetooth driver from manufacturer',
      'Turn Bluetooth off → wait 10 sec → turn back on',
      'Settings → Devices → Bluetooth → Remove device → Add again',
    ],
    tools: ['Device Manager', 'Settings'],
    time: '5–15 min',
  },
  {
    id: 'bt-002',
    title: 'Bluetooth adapter missing from Device Manager',
    category: 'Bluetooth',
    tags: ['bluetooth','driver','hardware'],
    severity: 'medium',
    causes: ['Bluetooth driver not installed', 'Bluetooth service disabled', 'WiFi/BT combo card fault'],
    steps: [
      'Action → Scan for hardware changes in Device Manager',
      'Services → Bluetooth Support Service → set to Automatic → Start',
      'Download and install Bluetooth driver from laptop manufacturer site',
      'Check if WiFi works — many laptops use Intel WiFi+BT combo card. If WiFi is also down: card may be dead or unseated',
      'Reseat M.2 or PCIe wireless card',
    ],
    tools: ['Device Manager', 'services.msc'],
    time: '15–30 min',
  },

  // ── Driver Issues ────────────────────────────────────────────
  {
    id: 'drv-001',
    title: 'BSOD after driver update',
    category: 'Drivers',
    tags: ['bsod','driver','rollback'],
    severity: 'critical',
    causes: ['Incompatible driver version', 'Driver conflict', 'Corrupt driver install'],
    steps: [
      'Boot into Safe Mode (hold Shift + Restart → Troubleshoot → Advanced → Startup Settings)',
      'Device Manager → find recently updated driver → right-click → Properties → Driver tab → Roll Back Driver',
      'If rollback not available: Uninstall driver → restart → do NOT reinstall until stable version found',
      'Check Windows Event Viewer → System → find Critical events at time of crash',
      'Use WhoCrashed to analyze minidump and identify faulty driver',
      'For GPU BSOD: use DDU in Safe Mode to completely remove GPU drivers, then reinstall',
    ],
    tools: ['Device Manager', 'DDU', 'WhoCrashed', 'Safe Mode'],
    time: '30–60 min',
  },
  {
    id: 'drv-002',
    title: 'Yellow exclamation mark on device — Code 43',
    category: 'Drivers',
    tags: ['driver','device-manager','code43'],
    severity: 'medium',
    causes: ['Driver reported failure', 'USB device drawing too much power', 'Device hardware fault'],
    steps: [
      'Unplug device → Device Manager → Uninstall device',
      'Reboot → replug device',
      'If Code 43 on GPU: usually driver issue — use DDU clean reinstall',
      'If Code 43 on USB device: try different USB port',
      'Check if device has its own power supply requirement',
      'Update or rollback driver',
      'If persistent: device hardware may be faulty',
    ],
    tools: ['Device Manager', 'DDU'],
    time: '15–30 min',
  },

  // ── BIOS / Boot ─────────────────────────────────────────────
  {
    id: 'boot-001',
    title: 'Laptop not booting — black screen on power on',
    category: 'Boot',
    tags: ['boot','bios','black-screen'],
    severity: 'critical',
    causes: ['RAM not seated properly', 'POST failure', 'BIOS corrupt', 'GPU failure', 'Power delivery issue'],
    steps: [
      'Remove and reseat RAM — clean contacts with eraser',
      'Try with one RAM stick at a time — test each slot',
      'Drain CMOS: remove battery + hold power button 30 sec',
      'Connect external monitor — check if laptop has display output',
      'Listen for POST beep codes — count and look up in BIOS manual',
      'Check power LED — if no lights at all, check power jack/cable',
      'Try booting without battery (AC only)',
      'If no display on external either: GPU or motherboard failure',
    ],
    tools: ['External monitor', 'POST beep code reference'],
    time: '30–120 min',
  },
  {
    id: 'boot-002',
    title: 'Windows fails to boot — spinning dots loop',
    category: 'Boot',
    tags: ['boot','windows','repair'],
    severity: 'high',
    causes: ['Corrupt system files', 'Failed Windows update', 'Boot configuration corrupt (BCD)', 'Drive failure'],
    steps: [
      'Force shutdown 3 times during boot → Automatic Repair screen should appear',
      'Advanced Options → Startup Repair → let Windows fix itself',
      'If that fails: Advanced Options → Command Prompt',
      'Run: sfc /scannow',
      'Run: DISM /Online /Cleanup-Image /RestoreHealth',
      'Run: bootrec /fixmbr and bootrec /rebuildbcd',
      'Check drive health — a failing drive causes boot loops',
      'Last resort: Windows clean install (backup data first)',
    ],
    tools: ['Windows Recovery Environment', 'cmd (recovery)', 'bootrec', 'sfc', 'DISM'],
    time: '30–180 min',
  },

  // ── Keyboard ────────────────────────────────────────────────
  {
    id: 'kb-001',
    title: 'Some keys on laptop keyboard not working',
    category: 'Keyboard',
    tags: ['keyboard','hardware','ribbon'],
    severity: 'medium',
    causes: ['Debris under keys', 'Keyboard ribbon cable loose', 'Key switch physically damaged', 'Driver issue'],
    steps: [
      'Use HackRore TestLab keyboard test to identify exactly which keys fail',
      'Try external USB keyboard — if external works, confirm it is hardware not software',
      'Use compressed air under keys to remove debris',
      'Device Manager → Keyboards → uninstall → reboot',
      'Open keyboard ribbon cable connector — clean and reseat',
      'If specific keys dead after liquid spill: keyboard replacement likely needed',
      'Source replacement keyboard by exact laptop model',
    ],
    tools: ['HackRore TestLab', 'Compressed air', 'Screwdrivers'],
    time: '15–60 min',
  },

  // ── Memory ──────────────────────────────────────────────────
  {
    id: 'ram-001',
    title: 'Random crashes, freezes or BSODs — RAM issue',
    category: 'RAM',
    tags: ['ram','bsod','memtest','crash'],
    severity: 'high',
    causes: ['Faulty RAM module', 'RAM not fully seated', 'RAM running at wrong speed (XMP issue)', 'RAM incompatible with motherboard'],
    steps: [
      'Run MemTest86 from USB for at least 2 full passes (overnight is best)',
      'If errors found: identify which stick by testing one at a time',
      'Remove all RAM → reseat firmly — listen for click',
      'Clean RAM contacts with eraser',
      'Try each slot individually',
      'Check BIOS RAM speed — if XMP/DOCP enabled, disable it and test at default',
      'Replace faulty module — match speed, type, and voltage',
    ],
    tools: ['MemTest86', 'CPU-Z'],
    time: '2–12 hours (memtest overnight)',
  },

  // ── Power ────────────────────────────────────────────────────
  {
    id: 'pwr-001',
    title: 'Laptop randomly shuts down without warning',
    category: 'Power',
    tags: ['shutdown','thermal','power','ram'],
    severity: 'high',
    causes: ['CPU/GPU overheating', 'Failing battery causing voltage drop', 'RAM issue', 'PSU/power adapter failing'],
    steps: [
      'Monitor temps with HWiNFO64 or HackRore — thermal shutdown at 95°C+',
      'If temps normal: run MemTest86 to rule out RAM',
      'Test with a different charger',
      'Check Event Viewer → System → look for Critical events before shutdown (Kernel-Power 41)',
      'Run powercfg /batteryreport — check battery capacity and health',
      'Check for Windows crash minidumps with WhoCrashed',
    ],
    tools: ['HWiNFO64', 'HackRore', 'Event Viewer', 'MemTest86', 'WhoCrashed'],
    time: '30–120 min',
  },

  // ── Windows ──────────────────────────────────────────────────
  {
    id: 'win-001',
    title: 'Windows activation shows "Not Activated"',
    category: 'Windows',
    tags: ['activation','license','windows'],
    severity: 'medium',
    causes: ['Hardware change triggered re-activation', 'License key used on too many machines', 'Digital license not linked to Microsoft account', 'Motherboard replaced'],
    steps: [
      'Settings → Activation → Troubleshoot → This device had a hardware change recently',
      'Sign into Microsoft account — if digital license is linked, it auto-activates',
      'Run: slmgr /ato to force activation attempt',
      'Run: slmgr /xpr to check expiry',
      'If OEM key: check sticker on base of laptop or under battery',
      'For fresh installs: use Magical Jelly Bean Keyfinder to extract key from old Windows installation',
    ],
    tools: ['slmgr', 'Settings', 'Keyfinder'],
    time: '10–30 min',
  },
  {
    id: 'win-002',
    title: 'Windows Update stuck or failing',
    category: 'Windows',
    tags: ['windows-update','repair','stuck'],
    severity: 'medium',
    causes: ['Windows Update cache corrupt', 'Windows Update service issue', 'Insufficient disk space', 'Conflicting software'],
    steps: [
      'Run Windows Update Troubleshooter (Settings → Troubleshoot)',
      'Stop Windows Update service: net stop wuauserv',
      'Delete contents of C:\\Windows\\SoftwareDistribution\\Download',
      'Start Windows Update service: net start wuauserv',
      'Run: DISM /Online /Cleanup-Image /RestoreHealth',
      'Run: sfc /scannow',
      'Ensure 15GB+ free disk space',
      'If specific update always fails: manually download from Microsoft Update Catalog',
    ],
    tools: ['cmd (admin)', 'DISM', 'sfc', 'Microsoft Update Catalog'],
    time: '20–60 min',
  },

  // ── Touchpad ─────────────────────────────────────────────────
  {
    id: 'tp-001',
    title: 'Touchpad not working or unresponsive',
    category: 'Touchpad',
    tags: ['touchpad','driver','bios'],
    severity: 'medium',
    causes: ['Fn + F9 (or similar) touchpad toggle disabled', 'Driver issue', 'Disabled in BIOS', 'Physical ribbon cable loose'],
    steps: [
      'Check Fn + touchpad key — look for touchpad icon on function keys',
      'Settings → Bluetooth & Devices → Touchpad → ensure it is enabled',
      'Device Manager → Mice and other pointing devices → look for Synaptics/ELAN/Alps device',
      'Update or reinstall touchpad driver',
      'BIOS → Internal Pointing Device → ensure Enabled',
      'If driver reinstall fails: download precision touchpad driver from laptop manufacturer',
      'Reseat touchpad ribbon cable',
    ],
    tools: ['Device Manager', 'Settings', 'BIOS'],
    time: '10–30 min',
  },

  // ── Performance ──────────────────────────────────────────────
  {
    id: 'perf-001',
    title: 'Laptop extremely slow — general performance',
    category: 'Performance',
    tags: ['performance','startup','ram','ssd'],
    severity: 'medium',
    causes: ['Too many startup programs', 'Malware', 'Full or failing hard drive', 'Insufficient RAM', 'Thermal throttling'],
    steps: [
      'Run HackRore — check health score, thermal throttling, startup items',
      'Task Manager → Startup → disable everything non-essential',
      'Check CPU/RAM usage in Task Manager — identify high-usage processes',
      'Scan for malware with Malwarebytes',
      'Check disk health with CrystalDiskInfo — failing HDD causes massive slowdown',
      'Check free disk space — Windows needs 15%+ free',
      'Check for thermal throttling — clean fan and repaste if CPU hits 90°C+',
      'Consider RAM upgrade if <8GB',
      'Consider SSD upgrade if still on HDD',
    ],
    tools: ['HackRore', 'Task Manager', 'Malwarebytes', 'CrystalDiskInfo'],
    time: '30–120 min',
  },

  // ── HDMI / Display Output ────────────────────────────────────
  {
    id: 'disp-003',
    title: 'HDMI port not outputting to external monitor',
    category: 'Display',
    tags: ['hdmi','external-monitor','gpu','driver'],
    severity: 'medium',
    causes: ['Wrong display mode selected', 'GPU driver issue', 'HDMI cable faulty', 'Port physically damaged'],
    steps: [
      'Press Win + P — try Duplicate, Extend, or Second screen only',
      'Try a different HDMI cable — cheap cables fail at 1080p60 and above',
      'Try a different monitor or TV to isolate the port vs the display',
      'Update GPU driver using DDU clean uninstall then fresh install',
      'Device Manager → Display adapters → check for errors',
      'Check HDMI port for bent or pushed-in pins',
      'If port is physically damaged: replace via motherboard HDMI port repair or use USB-C to HDMI adapter',
    ],
    tools: ['DDU', 'Device Manager', 'Win+P shortcut'],
    time: '10–40 min',
  },
  {
    id: 'disp-004',
    title: 'Screen brightness cannot be adjusted',
    category: 'Display',
    tags: ['brightness','driver','acpi','display'],
    severity: 'low',
    causes: ['Display driver missing ACPI brightness control', 'Monitor OSD brightness locked', 'Registry brightness value stuck'],
    steps: [
      'Update display adapter driver and monitor driver in Device Manager',
      'Device Manager → Monitors → Generic PnP Monitor → Update driver',
      'Settings → System → Display → Brightness — check if slider appears after driver update',
      'Run: powercfg /energy — check for display driver warnings',
      'Try installing manufacturer display utility (Intel Graphics Command Center, AMD Radeon Software)',
      'If Fn+brightness keys work but slider missing: install laptop manufacturer utility',
    ],
    tools: ['Device Manager', 'Intel Graphics Command Center', 'AMD Radeon Software'],
    time: '10–20 min',
  },

  // ── Audio ────────────────────────────────────────────────────
  {
    id: 'aud-001',
    title: 'No sound from laptop speakers',
    category: 'Audio',
    tags: ['audio','sound','driver','realtek'],
    severity: 'medium',
    causes: ['Audio driver corrupt or missing', 'Speaker muted in mixer', 'Wrong playback device selected', 'Speaker hardware failure'],
    steps: [
      'Right-click volume icon → Open Volume Mixer — check nothing is muted',
      'Right-click volume icon → Playback devices → ensure laptop speakers are set as default',
      'Device Manager → Sound, video and game controllers → check for Realtek/Intel audio device',
      'Uninstall audio device → reboot → let Windows reinstall',
      'Download Realtek Audio driver from laptop manufacturer support page',
      'Test with headphones — if headphones work but speakers don\'t: speaker hardware fault',
      'Open laptop and check speaker cable connection to motherboard',
    ],
    tools: ['Device Manager', 'Volume Mixer', 'Realtek Audio Console'],
    time: '15–45 min',
  },
  {
    id: 'aud-002',
    title: 'Headphone jack not working',
    category: 'Audio',
    tags: ['audio','headphone','jack','realtek'],
    severity: 'medium',
    causes: ['Audio driver not detecting jack insertion', 'Jack physically damaged', 'Realtek front panel setting wrong'],
    steps: [
      'Plug headphones in — check if Windows shows "Headphones" in playback devices',
      'Open Realtek Audio Console or HD Audio Manager → enable front panel jack detection',
      'Try different headphones to rule out headphone fault',
      'Inspect jack for debris or bent contacts — use torch and compressed air',
      'Uninstall Realtek driver → reboot → reinstall latest version',
      'If jack is loose or physically damaged: replace 3.5mm jack (soldering required on most laptops)',
    ],
    tools: ['Realtek HD Audio Manager', 'Realtek Audio Console'],
    time: '10–30 min',
  },

  // ── BIOS / Security ──────────────────────────────────────────
  {
    id: 'bios-001',
    title: 'BIOS password locked — cannot enter setup',
    category: 'BIOS',
    tags: ['bios','password','security','cmos'],
    severity: 'high',
    causes: ['Previous owner set BIOS password', 'Security chip enforcing password'],
    steps: [
      'Try common default passwords: blank, "admin", "password", "1234", last 8 digits of serial',
      'Remove CMOS battery for 5–15 minutes (resets BIOS on older laptops)',
      'On newer laptops: CMOS reset does NOT clear password — stored in EEPROM/TPM',
      'Short the CMOS reset jumper/pads on motherboard (location varies by model — search model + "BIOS reset")',
      'For HP/Dell/Lenovo business laptops: use manufacturer master password generator with service tag',
      'HP: HP BIOS Configuration Utility or contact HP support with proof of ownership',
      'Last resort: replace BIOS chip or motherboard',
    ],
    tools: ['HP BCU', 'Dell BIOS password tool', 'Manufacturer support'],
    time: '30 min – several hours',
  },
  {
    id: 'bios-002',
    title: 'Laptop showing "No Bootable Device" error',
    category: 'Boot',
    tags: ['boot','bios','ssd','hdd','no-boot'],
    severity: 'critical',
    causes: ['Boot order wrong in BIOS', 'SSD/HDD not detected', 'Windows bootloader corrupt', 'Drive physically failed'],
    steps: [
      'Enter BIOS (F2/F10/Del/Esc at startup depending on brand)',
      'Check Boot Order — ensure the correct drive is first',
      'Check Storage section — confirm SSD/HDD is detected by BIOS',
      'If drive not detected: reseat drive, check cable, try in another machine',
      'If drive detected but won\'t boot: boot from Windows USB → Startup Repair',
      'Advanced Options → Command Prompt → bootrec /fixmbr && bootrec /rebuildbcd',
      'If drive is detected but clicking: data recovery first, then replace drive',
    ],
    tools: ['BIOS setup', 'Windows Recovery USB', 'bootrec', 'CrystalDiskInfo'],
    time: '20–90 min',
  },

  // ── Charging / Power ─────────────────────────────────────────
  {
    id: 'pwr-002',
    title: 'Laptop charges slowly or shows "Plugged in, not charging"',
    category: 'Power',
    tags: ['charging','battery','driver','power'],
    severity: 'medium',
    causes: ['Wrong or underpowered charger', 'Battery driver issue', 'BIOS battery threshold setting', 'USB-C charging at lower wattage'],
    steps: [
      'Check charger wattage — must match or exceed laptop requirement (usually on sticker under laptop)',
      'If using USB-C charging: ensure charger is USB-PD and at correct wattage',
      'Device Manager → Batteries → Uninstall Microsoft ACPI battery device → reboot',
      'Check BIOS for "Battery Charge Threshold" or "Battery Conservation Mode" — disable if set',
      'Some laptops (Lenovo) have battery conservation mode at 60% — check Lenovo Vantage',
      'HP: check HP Support Assistant for battery calibration option',
      'Dell: check Dell Power Manager for charge limits',
    ],
    tools: ['Device Manager', 'Lenovo Vantage', 'Dell Power Manager', 'HP Support Assistant'],
    time: '10–25 min',
  },

  // ── Ports / Connectivity ─────────────────────────────────────
  {
    id: 'usb-003',
    title: 'SD card reader not detecting cards',
    category: 'USB',
    tags: ['sd-card','reader','driver'],
    severity: 'low',
    causes: ['Card reader driver missing', 'Dirty card reader contacts', 'SD card format not recognised', 'Card reader disabled in BIOS'],
    steps: [
      'Try a different SD card to rule out card fault',
      'Clean card reader slot with compressed air',
      'Device Manager → check for "Realtek PCIE CardReader" or similar — update driver',
      'Disk Management → check if card appears as unallocated (needs format)',
      'BIOS → check if SD card reader is enabled',
      'Download card reader driver from laptop manufacturer support page',
    ],
    tools: ['Device Manager', 'Disk Management'],
    time: '10–20 min',
  },
  {
    id: 'usb-004',
    title: 'USB-C port not charging or not recognising devices',
    category: 'USB',
    tags: ['usb-c','thunderbolt','charging','driver'],
    severity: 'medium',
    causes: ['USB-C controller driver issue', 'Port only supports data (not power delivery)', 'Thunderbolt driver missing', 'Physical port damage'],
    steps: [
      'Not all USB-C ports support charging — check laptop manual for which ports support Power Delivery',
      'Device Manager → Universal Serial Bus controllers → look for Thunderbolt/Intel USB-C controller',
      'Download Intel Thunderbolt driver from manufacturer site',
      'Try a different USB-C cable — cables vary widely in supported features',
      'Test with a known-good USB-C device to isolate port vs device',
      'Inspect port for debris or bent pins — USB-C ports are fragile',
    ],
    tools: ['Device Manager', 'Intel Thunderbolt software'],
    time: '15–30 min',
  },

  // ── OS / Software ────────────────────────────────────────────
  {
    id: 'win-003',
    title: 'Windows Explorer keeps crashing or freezing',
    category: 'Windows',
    tags: ['windows','explorer','crash','shell'],
    severity: 'medium',
    causes: ['Corrupt shell extension (context menu handler)', 'Corrupt Windows system files', 'Faulty third-party software', 'Low memory'],
    steps: [
      'Run: sfc /scannow in elevated Command Prompt',
      'Run: DISM /Online /Cleanup-Image /RestoreHealth',
      'Use ShellExView (NirSoft) to disable third-party shell extensions one by one',
      'Check Event Viewer → Application → look for Explorer.exe faults with faulting module name',
      'Disable thumbnail previews: Folder Options → View → "Always show icons, never thumbnails"',
      'Check for recently installed software — uninstall and test',
      'Create new user account — if Explorer works there, issue is profile corruption',
    ],
    tools: ['sfc', 'DISM', 'ShellExView (NirSoft)', 'Event Viewer'],
    time: '20–60 min',
  },
  {
    id: 'win-004',
    title: 'High disk usage (100%) constantly in Task Manager',
    category: 'Performance',
    tags: ['performance','disk','ssd','windows-search','superfetch'],
    severity: 'medium',
    causes: ['Windows Search indexing', 'SysMac / Superfetch thrashing on HDD', 'Windows Update downloading', 'Malware', 'Failing drive causing retries'],
    steps: [
      'Check disk health first — a failing drive causes constant 100% as Windows retries read errors',
      'Task Manager → Details tab → sort by Disk — identify which process is causing it',
      'If SearchIndexer.exe: Settings → Search → Windows Search → Rebuild index or disable enhanced search',
      'If SysMain (Superfetch): services.msc → SysMain → Stop + Disable (helps most on HDDs)',
      'If Windows Update: let it finish — usually resolves in 30 min',
      'Scan for malware with Malwarebytes',
      'Upgrade from HDD to SSD — this permanently fixes most 100% disk issues',
    ],
    tools: ['Task Manager', 'services.msc', 'CrystalDiskInfo', 'Malwarebytes'],
    time: '15–60 min',
  },
  {
    id: 'win-005',
    title: 'Computer clock keeps resetting to wrong time',
    category: 'Windows',
    tags: ['time','clock','cmos','battery'],
    severity: 'low',
    causes: ['CMOS battery dead (coin cell on motherboard)', 'Windows Time service not running', 'Time zone set incorrectly'],
    steps: [
      'Settings → Time & Language → sync time — if sync fails consistently: CMOS battery issue',
      'Services.msc → Windows Time → Start + set to Automatic',
      'Run: w32tm /resync /force to force NTP sync',
      'If time resets after every shutdown: CMOS battery (CR2032) is dead — replace it',
      'CMOS battery is on the motherboard — small coin cell, usually easy to access',
      'Cost: ₹20–50 (CR2032 battery)',
    ],
    tools: ['services.msc', 'w32tm command'],
    time: '5–20 min',
  },

  // ── POST / Hardware ──────────────────────────────────────────
  {
    id: 'boot-003',
    title: 'Laptop beeps on startup (POST beep codes)',
    category: 'Boot',
    tags: ['bios','post','beep','ram','gpu'],
    severity: 'high',
    causes: ['RAM failure (most common)', 'GPU failure', 'CPU issue', 'Motherboard failure'],
    steps: [
      'Count beep pattern carefully — beep codes are manufacturer-specific',
      'AMI BIOS: 1 beep = POST ok, 3 beeps = RAM failure, 8 beeps = GPU failure',
      'Award BIOS: 1 long 2 short = video card error, continuous beeps = RAM',
      'Phoenix BIOS: listen for groups (pause between groups)',
      'Search exact beep pattern + laptop brand + model for specific meaning',
      'Most common fix: remove and reseat RAM sticks — clean contacts with eraser',
      'Test with one RAM stick at a time in different slots',
    ],
    tools: ['Manufacturer BIOS beep code reference'],
    time: '20–60 min',
  },

  // ── Motherboard / Hardware ───────────────────────────────────
  {
    id: 'mb-001',
    title: 'Liquid spill damage — what to do immediately',
    category: 'Hardware',
    tags: ['liquid','spill','water-damage','immediate'],
    severity: 'critical',
    causes: ['Water, coffee, tea, juice spilled on laptop'],
    steps: [
      '⚠ IMMEDIATELY power off — hold power button until it shuts down',
      '⚠ Remove charger, then remove battery if removable',
      'Turn laptop upside down — let liquid drain out',
      'Do NOT press power to test if it works — this causes short circuit damage',
      'Open the laptop if possible — remove all visible moisture with lint-free cloth',
      'Leave open in a warm dry area for 48–72 hours minimum — do NOT use hairdryer',
      'Isopropyl alcohol (90%+) can clean dried residue from PCB — apply gently with soft brush',
      'After thorough drying: try powering on. If no power, check fuses on motherboard',
      'Sugary drinks (coffee, juice) cause corrosion — professional PCB cleaning recommended',
    ],
    tools: ['IPA 90%+', 'Soft brush', 'Lint-free cloth', 'Screwdrivers'],
    time: '48–72 hours drying + repair',
  },

  // ── Network / VPN ────────────────────────────────────────────
  {
    id: 'net-001',
    title: 'Ethernet port not working',
    category: 'Network',
    tags: ['ethernet','lan','driver','network'],
    severity: 'medium',
    causes: ['Ethernet driver missing or corrupt', 'Cable or port faulty', 'Network adapter disabled'],
    steps: [
      'Check link light on ethernet port — if no light: cable or port issue',
      'Try a different ethernet cable',
      'Try connecting directly to router (bypass any switch)',
      'Device Manager → Network Adapters → check for ethernet adapter (Realtek/Intel)',
      'Right-click adapter → Enable if disabled',
      'Update ethernet driver from manufacturer site',
      'Uninstall adapter → reboot → let Windows reinstall',
    ],
    tools: ['Device Manager'],
    time: '10–25 min',
  },
  {
    id: 'net-002',
    title: 'VPN causing no internet access',
    category: 'Network',
    tags: ['vpn','network','dns','routing'],
    severity: 'low',
    causes: ['VPN killing switch enabled', 'DNS leak blocking all traffic', 'Split tunneling not configured'],
    steps: [
      'Disconnect VPN — confirm internet returns',
      'Check VPN app for "Kill Switch" setting — disable if not needed',
      'Flush DNS: ipconfig /flushdns then reconnect VPN',
      'Try a different VPN server location',
      'netsh int ip reset to reset TCP/IP stack',
      'Uninstall and reinstall VPN client',
      'Check Windows Firewall — VPN may have added blocking rules',
    ],
    tools: ['ipconfig', 'netsh', 'VPN app'],
    time: '5–20 min',
  },

  // ── GPU ──────────────────────────────────────────────────────
  {
    id: 'gpu-001',
    title: 'GPU not detected or showing in Device Manager with error',
    category: 'Drivers',
    tags: ['gpu','driver','nvidia','amd','device-manager'],
    severity: 'high',
    causes: ['Corrupt or incompatible GPU driver', 'GPU disabled in Device Manager', 'Overheating causing GPU to shut off', 'GPU hardware failure'],
    steps: [
      'Download DDU (Display Driver Uninstaller) and run in Safe Mode',
      'DDU: Clean and restart — completely removes all GPU driver traces',
      'Download fresh driver from NVIDIA/AMD official site — NOT from Windows Update',
      'NVIDIA: use GeForce Experience or manual driver from nvidia.com',
      'AMD: use Radeon Software from amd.com',
      'After install: check Device Manager — should show without yellow warning',
      'If GPU shows Code 43 after clean reinstall: check GPU temp (may be throttling from heat)',
      'Run FurMark for 5 minutes — if it crashes immediately: GPU hardware issue',
    ],
    tools: ['DDU', 'GPU-Z', 'FurMark', 'HWiNFO64'],
    time: '30–60 min',
  },

  // ── Recovery ─────────────────────────────────────────────────
  {
    id: 'rec-001',
    title: 'Need to factory reset Windows without losing files',
    category: 'Windows',
    tags: ['reset','factory','windows','recovery'],
    severity: 'low',
    causes: ['Software issues requiring clean state', 'Preparing for resale'],
    steps: [
      'Settings → Update & Security → Recovery → Reset this PC',
      'Choose "Keep my files" to preserve personal data (removes apps and settings)',
      'Choose "Remove everything" for a clean wipe (for resale)',
      'If selling: choose "Remove everything" → "Remove files and clean the drive" for secure wipe',
      'Ensure charger is connected — reset takes 1–3 hours',
      'Create a Windows recovery drive first as backup before starting',
    ],
    tools: ['Settings → Recovery', 'Windows Recovery USB (backup)'],
    time: '1–3 hours',
  },
  {
    id: 'rec-002',
    title: 'Recovering files from a dead / non-booting laptop',
    category: 'Storage',
    tags: ['data-recovery','files','dead-laptop','ubuntu'],
    severity: 'high',
    causes: ['Windows corrupt but drive is physically fine', 'Need data before wiping'],
    steps: [
      'Create Ubuntu/Linux live USB using Rufus',
      'Boot target laptop from USB (change boot order in BIOS)',
      'Ubuntu will load without touching the Windows drive',
      'Connect external USB drive → open Files → copy data from Windows drive to USB',
      'Alternative: remove HDD/SSD → put in USB enclosure → connect to another PC',
      'If drive is encrypted with BitLocker: you need the recovery key from Microsoft account',
      'If drive has hardware failure: professional data recovery required (do not attempt DIY)',
    ],
    tools: ['Rufus', 'Ubuntu live USB', 'USB HDD enclosure', 'Recuva'],
    time: '30–120 min',
  },

  // ── Printing / Peripherals ───────────────────────────────────
  {
    id: 'per-001',
    title: 'External mouse or keyboard not working after plugging in',
    category: 'USB',
    tags: ['mouse','keyboard','usb','hid','driver'],
    severity: 'low',
    causes: ['USB port power issue', 'HID driver glitch', 'Device requires additional driver'],
    steps: [
      'Try a different USB port — especially avoid USB hubs initially',
      'Try the device on another computer — confirm it works',
      'Device Manager → Human Interface Devices → look for errors',
      'Uninstall HID-compliant device entries → reboot → replug',
      'Check Power Management for USB root hub — uncheck "allow computer to turn off"',
      'For gaming mice/keyboards: install vendor software (Logitech G Hub, Razer Synapse)',
    ],
    tools: ['Device Manager'],
    time: '5–15 min',
  },

  // ── Security ─────────────────────────────────────────────────
  {
    id: 'sec-001',
    title: 'Laptop running slow after virus / malware infection',
    category: 'Performance',
    tags: ['malware','virus','security','cleanup'],
    severity: 'high',
    causes: ['Active malware consuming resources', 'Residual malware processes', 'Modified startup entries'],
    steps: [
      'Boot into Safe Mode (hold Shift + Restart → Troubleshoot → Startup Settings → Safe Mode with Networking)',
      'Download and run Malwarebytes Free — full scan',
      'Download and run AdwCleaner (Malwarebytes) — removes adware',
      'Run Windows Defender offline scan: Settings → Virus protection → Scan options → Microsoft Defender Offline',
      'Check Task Manager for unknown high-CPU processes → search process name online',
      'Check startup items: msconfig → Startup or Task Manager → Startup tab',
      'After cleanup: change all passwords from a different device',
      'If infection was severe: clean Windows reinstall is the most reliable fix',
    ],
    tools: ['Malwarebytes', 'AdwCleaner', 'Windows Defender', 'msconfig'],
    time: '30–120 min',
  },
]

export const CATEGORIES = [...new Set(KB.map(e => e.category))].sort()
export const ALL_TAGS    = [...new Set(KB.flatMap(e => e.tags))].sort()
